gsap.from("#img1",{
    delay:0.4,
    opacity:0,
    duration:1,
    y:60
})
gsap.from("#img2",{
    delay:0.4,
    opacity:0,
    duration:1,
    x:60
})
gsap.from("#img5",{
    delay:0.4,
    opacity:0,
    duration:1,
    y:-60
})
gsap.from("#main h1",{
    delay:0.4,
    opacity:0,
    duration:1,
    y:-60
})